env: "dev"
MongoURI: "mongodb+srv://rohit:rohit123@cluster0.60lubst.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
storage_path: "storage/storage.db"
http_server:
  address: "localhost:8082"
